#!/bin/bash -e

# copy the docker config file from $SNAP into $SNAP_COMMON if it doesn't exist
if [ ! -f "$SNAP_DATA/config/daemon.json" ]; then
    mkdir -p "$SNAP_DATA/config"
    cp "$SNAP/config/daemon.json" "$SNAP_DATA/config/daemon.json"
fi

# we need copy the config file into $SNAP_COMMON where it can be modified
# but also need to modify the "homedir" root level spec in the yaml to be
# "$SNAP_COMMON/var/lib/iotedge"
# as well as the management + workload uri's to live in a snap specific 
# portion of /run that is writable from within the snap
mkdir -p "$SNAP_COMMON/etc/iotedge"
mkdir -p "$SNAP_COMMON/var/lib/iotedge"
mkdir -p "/run/snap.$SNAP_INSTANCE_NAME/iotedge"
cat "$SNAP/etc/iotedge/config.yaml" | \
    sed -e "s@homedir: \"/var/lib/iotedge\"@homedir: \"$SNAP_COMMON/var/lib/iotedge\"@" \
    -e "s@management_uri: \"unix:///var/run/iotedge/mgmt.sock\"@management_uri: \"unix:///run/snap.$SNAP_INSTANCE_NAME/iotedge/mgmt.sock\"@" \
    -e "s@workload_uri: \"unix:///var/run/iotedge/workload.sock\"@workload_uri: \"unix:///run/snap.$SNAP_INSTANCE_NAME/iotedge/workload.sock\"@" \
    -e "s@management_uri: \"fd://iotedge.mgmt.socket\"@management_uri: \"unix:///run/snap.$SNAP_INSTANCE_NAME/iotedge/mgmt.sock\"@" \
    -e "s@workload_uri: \"fd://iotedge.socket\"@workload_uri: \"unix:///run/snap.$SNAP_INSTANCE_NAME/iotedge/workload.sock\"@" \
    > "$SNAP_COMMON/etc/iotedge/config.yaml"

# also disable the service before installing so that it doesn't cause the 
# installation to be aborted
snapctl stop --disable "$SNAP_NAME.iotedged"
